routes/admin.php
<?php
Route::get('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

Route::get('/dashboard', 'HomeController@dashboard');
Route::get('/', 'HomeController@dashboard');

Route::group(['prefix' => '/home'], function () {
    Route::get('', 'HomeModuleController@index');
    Route::post('update', 'HomeModuleController@update');
});

// Profile
Route::group(['prefix' => '/profile'], function () {
    Route::get('', 'ProfileController@index');
    Route::post('save-information', 'ProfileController@saveInformation');
    Route::post('change-password', 'ProfileController@changePassword');
});

// Modules
Route::group(['prefix' => '/modules', 'middleware' => 'check-module:modules'], function () {
    Route::get('', 'ModulesController@index');
    Route::post('{id}/change-status', 'ModulesController@changeStatus');
});

// Users
Route::group(['middleware' => ['permission:view-user']], function () {
    Route::group(['prefix' => '/user'], function () {
        Route::get('', 'UserController@index');
        Route::get('add', 'UserController@add')->middleware(['permission:add-user']);
        Route::post('save', 'Auth\RegisterController@register')->middleware(['permission:add-user']);
        Route::get('{id}/edit', 'UserController@edit')->middleware(['permission:edit-user']);
        Route::get('{id}/delete', 'UserController@delete')->middleware(['permission:delete-user']);
        Route::post('save-permission', 'UserController@savePermission')->middleware(['permission:edit-permission']);
        Route::post('save-password', 'UserController@savePassword')->middleware(['permission:user-change-password']);
        Route::post('save-information', 'UserController@saveInformation')->middleware(['permission:edit-user']);
        Route::post('{id}/change-user-status', 'UserController@changeUserStatus');
    });
});

// Pages Module
Route::group(['prefix' => '/pages', 'middleware' => ['check-module:pages', 'permission:view-pages']], function () {
    Route::any('', 'PagesController@index');
    Route::get('add', 'PagesController@add')->middleware(['permission:add-page']);
    Route::post('store', 'PagesController@store')->middleware(['permission:add-page']);
    Route::get('{id}/edit', 'PagesController@edit')->middleware(['permission:edit-page']);
    Route::post('update', 'PagesController@update')->middleware(['permission:edit-page']);
    Route::get('{id}/delete', 'PagesController@delete')->middleware(['permission:delete-page']);
    Route::get('{id}/preview', 'PagesController@preview');

    Route::get('categories', 'PagesController@categories');
    Route::get('add-category', 'PagesController@addCategory')->middleware(['permission:add-page-category']);
    Route::post('store-category', 'PagesController@storeCategory')->middleware(['permission:add-page-category']);
    Route::get('{id}/edit-category', 'PagesController@editCategory')->middleware(['permission:edit-page-category']);
    Route::post('update-category', 'PagesController@updateCategory')->middleware(['permission:edit-page-category']);
    Route::get('{id}/delete-category', 'PagesController@deleteCategory')->middleware(['permission:delete-page-category']);

    Route::post('{id}/change-category-status', 'PagesController@changeCategoryStatus');
    Route::post('{id}/change-page-status', 'PagesController@changePageStatus');
    Route::get('forget', 'PagesController@emptyFilter');
    Route::any('sort', 'PagesController@sort')->middleware(['permission:sort-page']);
});

// News Module
Route::group(['prefix' => '/news', 'middleware' => ['check-module:news', 'permission:view-news']], function () {
    Route::any('', 'NewsController@index');
    Route::get('add', 'NewsController@add')->middleware(['permission:add-news']);
    Route::post('store', 'NewsController@store')->middleware(['permission:add-news']);
    Route::get('{id}/edit', 'NewsController@edit')->middleware(['permission:edit-news']);
    Route::post('update', 'NewsController@update')->middleware(['permission:edit-news']);
    Route::get('{id}/delete', 'NewsController@delete')->middleware(['permission:delete-news']);
    Route::get('{id}/preview', 'NewsController@preview');

    Route::get('categories', 'NewsController@categories');
    Route::get('add-category', 'NewsController@addCategory')->middleware(['permission:add-news-category']);
    Route::post('store-category', 'NewsController@storeCategory')->middleware(['permission:add-news-category']);
    Route::get('{id}/edit-category', 'NewsController@editCategory')->middleware(['permission:edit-news-category']);
    Route::post('update-category', 'NewsController@updateCategory')->middleware(['permission:edit-news-category']);
    Route::get('{id}/delete-category', 'NewsController@deleteCategory')->middleware(['permission:delete-news-category']);
    Route::get('sort-category', 'NewsController@sortCategory')->middleware(['permission:sort-news-category']);

    Route::post('{id}/change-category-status', 'NewsController@changeCategoryStatus');
    Route::post('{id}/change-status', 'NewsController@changeStatus');
    Route::get('forget', 'NewsController@emptyFilter');
});

// FAQs Module
Route::group(['prefix' => '/faqs', 'middleware' => ['check-module:faqs', 'permission:view-faqs']], function () {
    Route::any('', 'FaqsController@index');
    Route::get('add', 'FaqsController@add')->middleware(['permission:add-faqs']);
    Route::post('store', 'FaqsController@store')->middleware(['permission:add-faqs']);
    Route::get('{id}/edit', 'FaqsController@edit')->middleware(['permission:edit-faqs']);
    Route::post('update', 'FaqsController@update')->middleware(['permission:edit-faqs']);
    Route::get('{id}/delete', 'FaqsController@delete')->middleware(['permission:delete-faqs']);
    Route::get('{id}/preview', 'FaqsController@preview');

    Route::get('categories', 'FaqsController@categories');
    Route::get('add-category', 'FaqsController@addCategory')->middleware(['permission:add-faqs-category']);
    Route::post('store-category', 'FaqsController@storeCategory')->middleware(['permission:add-faqs-category']);
    Route::get('{id}/edit-category', 'FaqsController@editCategory')->middleware(['permission:edit-faqs-category']);
    Route::post('update-category', 'FaqsController@updateCategory')->middleware(['permission:edit-faqs-category']);
    Route::get('{id}/delete-category', 'FaqsController@deleteCategory')->middleware(['permission:delete-faqs-category']);
    Route::get('sort-category', 'FaqsController@sortCategory')->middleware(['permission:sort-faqs-category']);

    Route::post('{id}/change-faq-status', 'FaqsController@changeFaqStatus');
    Route::post('{id}/change-category-status', 'FaqsController@changeCategoryStatus');
    Route::get('forget', 'FaqsController@emptyFilter');
    Route::get('sort', 'FaqsController@sort')->middleware(['permission:sort-faq']);
});

// Gallery Module
Route::group(['prefix' => '/gallery', 'middleware' => ['check-module:gallery', 'permission:view-gallery']], function () {
    Route::any('', 'GalleryController@index');
    Route::get('add', 'GalleryController@add')->middleware(['permission:add-image']);
    Route::post('store', 'GalleryController@store')->middleware(['permission:add-image']);
    Route::get('{id}/edit', 'GalleryController@edit')->middleware(['permission:edit-image']);
    Route::post('update', 'GalleryController@update')->middleware(['permission:edit-image']);
    Route::get('{id}/delete', 'GalleryController@delete')->middleware(['permission:delete-image']);
    Route::get('{id}/show', 'GalleryController@show');

    Route::get('categories', 'GalleryController@categories');
    Route::get('add-category', 'GalleryController@addCategory')->middleware(['permission:add-gallery-category']);
    Route::post('store-category', 'GalleryController@storeCategory')->middleware(['permission:add-gallery-category']);
    Route::get('{id}/edit-category', 'GalleryController@editCategory')->middleware(['permission:edit-gallery-category']);
    Route::post('update-category', 'GalleryController@updateCategory')->middleware(['permission:edit-gallery-category']);
    Route::get('{id}/delete-category', 'GalleryController@deleteCategory')->middleware(['permission:delete-gallery-category']);
    Route::get('sort-category', 'GalleryController@sortCategory')->middleware(['permission:sort-gallery-category']);

    Route::post('{id}/change-category-status', 'GalleryController@changeCategoryStatus');
    Route::post('{id}/change-status', 'GalleryController@changeStatus')->middleware(['permission:edit-image']);
    Route::post('image-sort', 'GalleryController@imageSort')->middleware(['permission:edit-image']);
    Route::get('forget', 'GalleryController@emptyFilter');
});

// Members Module
Route::group(['prefix' => '/members', 'middleware' => ['check-module:members', 'permission:view-members']], function () {
    Route::any('', 'MembersController@index');
    Route::get('add', 'MembersController@add')->middleware(['permission:add-members']);
    Route::post('store', 'MembersController@store')->middleware(['permission:add-members']);
    Route::get('{id}/edit', 'MembersController@edit')->middleware(['permission:edit-members']);
    Route::post('update', 'MembersController@update')->middleware(['permission:edit-members']);
    Route::get('{id}/delete', 'MembersController@delete')->middleware(['permission:delete-members']);
    Route::get('{id}/show', 'MembersController@show');

    Route::get('types', 'MembersController@types');
    Route::get('add-type', 'MembersController@addType')->middleware(['permission:add-members-type']);
    Route::post('store-type', 'MembersController@storeType')->middleware(['permission:add-members-type']);
    Route::get('{id}/edit-type', 'MembersController@editType')->middleware(['permission:edit-members-type']);

routes/web.php
<?php 
// Home Page
Route::get('/', 'HomeController@index');
Route::get('/index', 'HomeController@indexDev');  // To bypass holding page in development mode

// Content Styles
Route::get('/style-guide', 'HomeController@styleGuide');

// Contact Form
Route::group(['prefix' => '/contact'], function () {
    Route::get('/', 'ContactController@index');
    Route::post('save-message', 'ContactController@saveMessage');
    Route::get('success', 'ContactController@success');
});

// Pages Module
Route::group(['prefix' => '/pages'], function () {
    Route::get('{category}', 'PagesController@index');    
	Route::get('{category}/{page}', 'PagesController@index');    
});

// News Module
Route::group(['prefix' => '/news'], function () {
	Route::get('', 'NewsController@list'); 	
	
	Route::get('archive', 'NewsController@archive'); 
	Route::get('archive/{age}', 'NewsController@archive'); 
	
    Route::get('{category}', 'NewsController@list');    
	Route::get('{category}/{page}', 'NewsController@item'); 
	
});

// Faqs Module
Route::group(['prefix' => '/faqs'], function () {
	Route::get('', 'FaqsController@index'); 
    Route::get('{category}', 'FaqsController@index');    	
});

// Documents Module
Route::group(['prefix' => '/documents'], function () {
	Route::get('', 'DocumentsController@index'); 
    Route::get('{category}', 'DocumentsController@index');    	
});

// Gallery Module
Route::group(['prefix' => '/gallery'], function () {
	Route::get('', 'GalleryController@index'); 
    Route::get('{category}', 'GalleryController@detail');    	
});

// Projects Module
Route::group(['prefix' => '/projects'], function () {
	Route::get('', 'ProjectsController@list'); 			
	
    Route::get('{category}', 'ProjectsController@list');    
	Route::get('{category}/{page}', 'ProjectsController@item');
});

// Team Module
Route::group(['prefix' => '/team'], function () {
    Route::get('', 'TeamController@index');
    Route::get('{category}', 'TeamController@index');
    Route::get('{category}/{member}', 'TeamController@member');
});

// ***********
// Shop Module
// ***********
Route::group(['prefix' => '/products', 'as' => 'products.'], function() {
    Route::get('', 'ProductsController@list')->name('list'); 	
	
	Route::get('{category}', 'ProductsController@list');    
	Route::get('{category}/{page}', 'ProductsController@item'); 	
});

Route::group(['prefix' => 'cart', 'as' => 'cart.'], function() {
    Route::get('show', 'CartController@show')->name('show');
    Route::post('add/{product}', 'CartController@add')->name('add');
    Route::post('remove/{cart_item}', 'CartController@remove')->name('remove');
});

Route::group(['prefix' => 'checkout', 'as' => 'checkout.'], function() {
    Route::get('show', 'CheckoutController@show')->name('show');	
    Route::post('submit', 'CheckoutController@submit')->name('submit');
		
	Route::get('complete/{order}', 'CheckoutController@complete')->name('complete');
	Route::get('cancel/{order}', 'CheckoutController@cancel')->name('cancel');
});
// ***********

// Testimonials Module
Route::group(['prefix' => '/testimonials'], function () {
    Route::get('', 'TestimonialsController@index');
});

app/Http/Controllers/Site/CartController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use Vanilo\Cart\Contracts\CartItem;
use Vanilo\Cart\Facades\Cart;
use Vanilo\Product\Contracts\Product;

class CartController extends Controller
{
    public function add(Product $product)
    {
        Cart::addItem($product);

        return redirect()->route('cart.show');
    }

    public function remove(CartItem $cart_item)
    {
        Cart::removeItem($cart_item);

        return redirect()->route('cart.show');
    }

    public function show()
    {
        return view('site/cart/show');
    }
}

app/Http/Controllers/Site/ContactController.php
<?php

namespace App\Http\Controllers\Site;

use App\ContactMessages;
use App\Http\Controllers\Controller;
use App\Mail\ContactMessageAdmin;
use App\Mail\ContactMessageUser;
use App\Setting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Validator, Illuminate\Support\Facades\Input, Redirect;

class ContactController extends Controller
{
    public function index(){

        $fields = Setting::where('key', '=', 'contact-form-fields')->first();

        // Contact Details
        $contact_details = Setting::where('key', '=', 'contact-details')->first();

        $form = $fields->value;

        if(old('name')){
            $fields = json_decode($fields->value);
            foreach ($fields as $field){
                $field->value = old($field->name);
            }

            $form = json_encode($fields);
        }

        return view('site/contact/contact', array(
            'contact_form' => $form,
            'contact_details' => $contact_details->value
        ));
    }

    public function saveMessage(Request $request)
    {

        $rules = array(
            'g-recaptcha-response' => 'required|recaptcha'
        );

        $messages = [
            'g-recaptcha-response.required' => 'Please verify yourself',
            'g-recaptcha-response.recaptcha' => 'Please verify yourself'
        ];

        $validator = Validator::make($request->all(), $rules, $messages);
        if ($validator->fails()) {
            return redirect('contact')->withErrors($validator)->withInput();
        }

        $fields = Setting::where('key', '=', 'contact-form-fields')->first();
        $fields = json_decode($fields->value);

        $data = array();

        foreach ($fields as $field){

            if($field->type!='header' && $field->type!='paragraph'){

                if($field->type=='date'){
                    $date_array = explode('-',$request->{$field->name});
                     $request->{$field->name} = $date_array[2].'-'.$date_array[1].'-'.$date_array[0];
                }

                $data_field['label'] = $field->label;
                $data_field['field'] = $field->name;
                $data_field['value'] = $request->{$field->name};
                array_push($data, $data_field);
            }
        }

        $message = new ContactMessages();
        $message->data = json_encode($data);
        $message->save();

		$setting = Setting::where('key','=','contact-email')->first();
		$contactEmail = $setting->value;
		
		// Email Website Owner
        Mail::to($contactEmail)->send(new ContactMessageAdmin($message));
		
		// Email User
        Mail::to($request->email)->send(new ContactMessageUser($message));

        return \Redirect::to('contact/success');
    }

    public function success(){
		 // Contact Details
        $contact_details = Setting::where('key', '=', 'contact-details')->first();

        return view('site/contact/success', array(         
            'contact_details' => $contact_details->value
        ));
    }
}

app/Http/Controllers/Site/HomeController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Setting;

class HomeController extends Controller
{
    public function index(){

    	$settings = Setting::where('key', '=', 'company-name')->first();
        $company_name = $settings->value;

		if (env('APP_MODE') == "dev")  {
		   return view('site/holding', array(         
			'company_name' => $company_name,			
           ));	
		   
		} else  {
    	   return view('site/index');	
		}

    }
	
	public function indexDev(){ 		
		return view('site/index');			
    }
	
	public function styleGuide(){

    	return view('site/style-guide');

    }
}

resources/views/site/checkout/_billing_address.blade.php
<?php
//dd($errors);
?>
<h3>Billing Address</h3>

<div class="form-group form-group-sm row{{ $errors->has('billpayer.address.country_id') ? ' has-danger' : '' }} hidden-country">
    <label class="form-control-label col-md-2">{{ __('Country') }}</label>
    <div class="col-md-10">
        
        {{ Form::select('billpayer[address][country_id]', $countries->pluck('name', 'id'), 'NL', ['class' => 'form-control']) }}

        @if ($errors->has('billpayer.address.country_id'))
            <div class="form-control-feedback">{{ $errors->first('billpayer.address.country_id') }}</div>
        @endif
    </div>
</div>

<div class="form-group form-group-sm row{{ $errors->has('billpayer.address.address') ? ' has-danger' : '' }}">
    <label class="form-control-label col-md-2">{{ __('Address *') }}</label>
    <div class="col-md-10">
        {{ Form::text('billpayer[address][address]', null, ['class' => 'form-control', 'placeholder' => 'Address (Line 1)']) }}
        
        @if ($errors->has('billpayer.address.address'))
            <div class="form-control-feedback"><i class="fas fa-exclamation"></i> Address is required <!-- {{ $errors->first('billpayer.address.address') }} --></div>
        @endif
    </div>
</div>

<div class="form-group form-group-sm row{{ $errors->has('billpayer.address.address2') ? ' has-danger' : '' }}">
    <label class="form-control-label col-md-2"></label>
    <div class="col-md-10">
        {{ Form::text('billpayer[address][address2]', null, ['class' => 'form-control', 'placeholder' => 'Address (Line 2)']) }}
        
        @if ($errors->has('billpayer.address.address2'))
            <div class="form-control-feedback"><i class="fas fa-exclamation"></i> {{ $errors->first('billpayer.address.address2') }}</div>
        @endif
    </div>
</div>

<div class="form-group form-group-sm row{{ $errors->has('billpayer.address.postalcode') ? ' has-danger' : '' }}">    
    <label class="form-control-label col-md-2">{{ __('Suburb *') }}</label>
    <div class="col-md-10">
        {{ Form::text('billpayer[address][city]', null, ['class' => 'form-control', 'placeholder' => 'Suburb']) }}
        
        @if ($errors->has('billpayer.address.city'))
            <div class="form-control-feedback"><i class="fas fa-exclamation"></i> Suburb is required <!-- {{ $errors->first('billpayer.address.city') }} --></div>
        @endif
    </div>
</div>

<div class="form-group form-group-sm row{{ $errors->has('billpayer.address.province_id') ? ' has-danger' : '' }}">              
    <label class="form-control-label col-md-2">{{ __('State *') }}</label>
    <div class="col-md-10">
         {{ Form::select('billpayer[address][province_id]', $states->pluck('state', 'id'), 'NL', ['class' => 'form-control']) }}
         
         @if ($errors->has('billpayer.address.province_id'))
            <div class="form-control-feedback"><i class="fas fa-exclamation"></i> State is required <!-- {{ $errors->first('billpayer.address.province_id') }} --></div>
        @endif
    </div>
</div>
    
<div class="form-group form-group-sm row{{ $errors->has('billpayer.address.address') ? ' has-danger' : '' }}">    
    <label class="form-control-label col-md-2">{{ __('Postcode *') }}</label>
    <div class="col-md-10">
        {{ Form::text('billpayer[address][postalcode]', null, ['class' => 'form-control', 'placeholder' => 'Postcode']) }}
        
        @if ($errors->has('billpayer.address.postalcode'))
            <div class="form-control-feedback"><i class="fas fa-exclamation"></i> Postcode is required <!-- {{ $errors->first('billpayer.address.postalcode') }} --></div>
        @endif
    </div>
</div>

resources/views/site/checkout/_billpayer.blade.php
<h3>Bill To</h3>

<div class="form-group form-group-sm row{{ $errors->has('billpayer.firstname') ? ' has-danger' : '' }}">
    <label class="form-control-label col-md-2">{{ __('First Name *') }}</label>
    <div class="col-md-10">
            {{ Form::text('billpayer[firstname]', null, [
                    'class' => 'form-control',
                    'placeholder' => __('First name')
                ])
            }}

            @if ($errors->has('billpayer.firstname'))
                <div class="form-control-feedback"><i class="fas fa-exclamation"></i>  First name is required<!--{{ $errors->first('billpayer.firstname') }}--></div>
            @endif
    </div>
</div>
  
<div class="form-group form-group-sm row{{ $errors->has('billpayer.lastname') ? ' has-danger' : '' }}">
    <label class="form-control-label col-md-2">{{ __('Last Name *') }}</label>
    <div class="col-md-10">
            {{ Form::text('billpayer[lastname]', null, [
                    'class' => 'form-control',
                    'placeholder' => __('Last name')
                ])
            }}

            @if ($errors->has('billpayer.lastname'))
                <div class="form-control-feedback"><i class="fas fa-exclamation"></i>  Last name is required<!--{{ $errors->first('billpayer.firstname') }}--></div>
            @endif
    </div>
</div>  

<div class="form-group form-group-sm row{{ $errors->has('billpayer.email') ? ' has-danger' : '' }}">
    <label class="form-control-label col-md-2">{{ __('Email *') }}</label>
    <div class="col-md-10">
            {{ Form::text('billpayer[email]', null, [
                    'class' => 'form-control',
                    'placeholder' => __('Email')
                ])
            }}

            @if ($errors->has('billpayer.email'))
                <div class="form-control-feedback"><i class="fas fa-exclamation"></i>  Email is required<!--{{ $errors->first('billpayer.firstname') }}--></div>
            @endif
    </div>
</div>

<!--
<div class="form-group form-group-sm{{ $errors->has('type') ? ' has-danger' : '' }}">
    <div class="checkbox">
        <label>
            {{ Form::checkbox('billpayer[is_organization]', 1, null, [
                'v-model' => 'isOrganization'
                ])
            }}
            {{ __('Bill to Company') }}
        </label>
    </div>

    @if ($errors->has('type'))
        <div class="form-control-feedback">{{ $errors->first('type') }}</div>
    @endif
</div>

<div id="billpayer-organization" v-show="isOrganization">
    <div class="form-group form-group-sm{{ $errors->has('billpayer.company_name') ? ' has-danger' : '' }}">
        {{ Form::text('billpayer[company_name]', null, ['class' => 'form-control form-control-lg', 'placeholder' => __('Company name')]) }}
        @if ($errors->has('billpayer.company_name'))
            <div class="form-control-feedback">{{ $errors->first('billpayer.company_name') }}</div>
        @endif
    </div>

    <div class="form-group form-group-sm{{ $errors->has('billpayer.tax_nr') ? ' has-danger' : '' }}">
        {{ Form::text('billpayer[tax_nr]', null, ['class' => 'form-control', 'placeholder' => __('Tax no.')]) }}
        @if ($errors->has('billpayer.tax_nr'))
            <div class="form-control-feedback">{{ $errors->first('billpayer.tax_nr') }}</div>
        @endif
    </div>
</div>
-->

@include('site.checkout._billing_address', ['address' => $billpayer->getBillingAddress()])

resources/views/site/checkout/_shipping_address.blade.php
<div id="shipping-address" v-show="!shipToBillingAddress">
    <h3>Shipping Address</h3>

    <div class="form-group form-group-sm row{{ $errors->has('shippingAddress.name') ? ' has-danger' : '' }}">
        <label class="form-control-label col-md-2">{{ __('Name') }}</label>
        <div class="col-md-10">
            {{ Form::text('shippingAddress[name]', null, ['class' => 'form-control']) }}
        </div>
    </div>
    
    <div class="form-group form-group-sm row{{ $errors->has('shippingAddress.country_id') ? ' has-danger' : '' }} hidden-country">
        <label class="form-control-label col-md-2">{{ __('Country') }}</label>
        <div class="col-md-10">
            {{ Form::select('shippingAddress[country_id]', $countries->pluck('name', 'id'), 'NL', ['class' => 'form-control']) }}

            @if ($errors->has('shippingAddress.country_id'))
                <div class="form-control-feedback">{{ $errors->first('shippingAddress.country_id') }}</div>
            @endif
        </div>
    </div>
        
    <div class="form-group form-group-sm row{{ $errors->has('shippingAddress.address') ? ' has-danger' : '' }}">
        <label class="form-control-label col-md-2">{{ __('Address') }}</label>
        <div class="col-md-10">
            {{ Form::text('shippingAddress[address]', null, ['class' => 'form-control', 'placeholder' => 'Address (Line 1)']) }}
        </div>
    </div>
    
    

    <div class="form-group form-group-sm row{{ $errors->has('shippingAddress.postalcode') ? ' has-danger' : '' }}">        
        <label class="form-control-label col-md-2">{{ __('Suburb') }}</label>
        <div class="col-md-10">
            {{ Form::text('shippingAddress[city]', null, ['class' => 'form-control', 'placeholder' => 'Suburb']) }}
        </div>
	</div>
  
    <div class="form-group form-group-sm row{{ $errors->has('shippingAddress.address.province_id') ? ' has-danger' : '' }}">              
		<label class="form-control-label col-md-2">{{ __('State') }}</label>
		<div class="col-md-10">
			 {{ Form::select('shippingAddress[province_id]', $states->pluck('state', 'id'), 'NL', ['class' => 'form-control']) }}
		</div>
	</div>
   
    <div class="form-group form-group-sm row{{ $errors->has('billpayer.address.address') ? ' has-danger' : '' }}">             
        <label class="form-control-label col-md-2">{{ __('Postcode') }}</label>
        <div class="col-md-10">
            {{ Form::text('shippingAddress[postalcode]', null, ['class' => 'form-control', 'placeholder' => 'Postcode']) }}
        </div>
    </div>
</div>

resources/views/site/checkout/show.blade.php
@extends('site/layouts/app')

@section('content')

@include('site/partials/carousel-inner')

<div class="blog-masthead ">         
    <div class="container">

      <div class="row">      
        @include('site/partials/sidebar-products')
                     
        <div class="col-sm-8 blog-main">

          <div class="blog-post">           
            <h1 class="blog-post-title">Checkout</h1>
                @include('flash::message')     
                
                @unless ($checkout)
					<div class="alert alert-info">
						<p>Hey, nothing to check out here!</p>
					</div>
				@endunless

				@if ($checkout)
					<form id="checkout" action="{{ route('checkout.submit') }}" method="post">
						{{ csrf_field() }}

						@include('site.checkout._billpayer', ['billpayer' => $checkout->getBillPayer()])

						<div>
							<input type="hidden" name="ship_to_billing_address" value="0" />
							<div class="checkbox">
								<label>
									<input type="checkbox" name="ship_to_billing_address" value="1"
										   v-model="shipToBillingAddress">
									Ship to the same address
								</label>
							</div>
						</div>

						<hr>

						@include('site.checkout._shipping_address', ['address' => $checkout->getShippingAddress()])

						<h3>Total: {{ format_price($checkout->total()) }}</h3>

						<hr>

						<div>
							<button class="btn-checkout">Submit Order</button>
						</div>


					</form>
				@endif
            
          </div><!-- /.blog-post -->         
        </div><!-- /.blog-main -->        

      </div><!-- /.row -->

    </div><!-- /.container -->
@endsection
                                                                      
@section('scripts')
    <script src="{{ asset('js/site/app.js') }}"></script>
   
    @if ($checkout)
    <script>
        document.addEventListener("DOMContentLoaded", function(event) {
            new Vue({
                el: '#checkout',
                data: {
                    isOrganization: {{ old('billpayer.is_organization') ?: 0 }},
                    shipToBillingAddress: {{ old('ship_to_billing_address') ?? 1 }}
                }
            });
        });
    </script>
    @endif
@stop